//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAGINA_SUCURSAL_MEDICA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class administrador
    {
        public string id_adm { get; set; }
        public string nickname_adm { get; set; }
        public string nombre_adm { get; set; }
        public string contrasenia_adm { get; set; }
        public string direccion_adm { get; set; }
        public string direccion_ip_adm { get; set; }
    }
}
