//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAGINA_SUCURSAL_MEDICA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class citas
    {
        [Required(ErrorMessage ="Campo Requerido")]
        public string id_cita { get; set; }
        [Required(ErrorMessage = "Campo Requerido")]
        public string nombre_paciente { get; set; }
        [Required(ErrorMessage = "Campo Requerido")]
        public string nombre_medico_ { get; set; }
        [Required(ErrorMessage = "Campo Requerido")]
        public System.DateTime fecha_cita { get; set; }
        [Required(ErrorMessage = "Campo Requerido")]
        public string id_paciente { get; set; }
        [Required(ErrorMessage = "Campo Requerido")]
        public string id_medico { get; set; }
    }
}
