//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAGINA_SUCURSAL_MEDICA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class creacion_funcionario
    {
        public string nickNameParaIngresar { get; set; }
        public int cedula { get; set; }
        public string nombreCompleto { get; set; }
        public string correElectronico { get; set; }
        public string direccion { get; set; }
        public string lugarDeResidencia { get; set; }
        public string sedeDondeSePrestaraLaAtencion { get; set; }
        public string lugarDeNacimiento { get; set; }
        public string sedeDeAtencion { get; set; }
        public string contrasenia { get; set; }
        public System.DateTime fechaExppCedu { get; set; }
        public System.DateTime fechaDeNaciemiento { get; set; }
        public int numeroDeContacto { get; set; }
        public string labor_desempenia { get; set; }
    }
}
