//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAGINA_SUCURSAL_MEDICA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class creacion_usuario
    {
        [Required(ErrorMessage = "Campo requerido")]
        public string nickNameParaIngresar { get; set; }
        [Required(ErrorMessage = "Campo requerido")]
        public int cedula { get; set; }
        [Required(ErrorMessage = "Campo requerido")]
        public string nombreCompleto { get; set; }
        [Required(ErrorMessage = "Campo requerido")]
        public string correElectronico { get; set; }
        [Required(ErrorMessage = "Campo requerido")]
        public string direccion { get; set; }
        [Required(ErrorMessage = "Campo requerido")]
        public string lugarDeResidencia { get; set; }
        [Required(ErrorMessage = "Campo requerido")]
        public string sedeDondeSePrestaraLaAtencion { get; set; }
        [Required(ErrorMessage = "Campo requerido")]
        public string lugarDeNacimiento { get; set; }
        [Required(ErrorMessage = "Campo requerido")]
        public string sedeDeAtencion { get; set; }
        [Required(ErrorMessage = "Campo requerido")]
        public string contrasenia { get; set; }
        [Required(ErrorMessage = "Campo requerido")]
        public System.DateTime fechaExppCedu { get; set; }
        [Required(ErrorMessage = "Campo requerido")]
        public System.DateTime fechaDeNaciemiento { get; set; }
        [Required(ErrorMessage = "Campo requerido")]
        public int numeroDeContacto { get; set; }
    }
}
