//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAGINA_SUCURSAL_MEDICA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ingreso_usuaio
    {
        [Required(ErrorMessage ="El campo es requerido.")]
        public string nick_name_ingresar { get; set; }
        [Required(ErrorMessage = "El campo es requerido.")]
        public string contrasenia_usuario { get; set; }
    }
}
