//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAGINA_SUCURSAL_MEDICA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sucursualEntities : DbContext
    {
        public sucursualEntities()
            : base("name=sucursualEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<administrador> administrador { get; set; }
        public virtual DbSet<citas> citas { get; set; }
        public virtual DbSet<creacion_funcionario> creacion_funcionario { get; set; }
        public virtual DbSet<creacion_usuario> creacion_usuario { get; set; }
        public virtual DbSet<historial_clinico> historial_clinico { get; set; }
        public virtual DbSet<ingreso_usuaio> ingreso_usuaio { get; set; }
        public virtual DbSet<medico> medico { get; set; }
        public virtual DbSet<no_afiliados> no_afiliados { get; set; }
        public virtual DbSet<paciente> paciente { get; set; }
        public virtual DbSet<recuperar_contrasenia> recuperar_contrasenia { get; set; }
    }
}
