//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAGINA_SUCURSAL_MEDICA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class no_afiliados
    {
        public string id_no_afiliados { get; set; }
        public string correo_electronico { get; set; }
        public string contrasenia { get; set; }
        public string nombre_usuario { get; set; }
    }
}
